spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      chroma:
        client:
          host: ${CHROMA_HOST:http://localhost}
          port: ${CHROMA_PORT:8000}
        collection-name: airline-reviews
        initialize-schema: true
  main:
    web-application-type: none

logging:
  level:
    root: INFO
    com.springai.rag: DEBUG
  